name: Notify Integration Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "A semver"
        default: 0.0.1
        required: false
jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout integration-release-action
        uses: actions/checkout@v2
        with:
          repository: BrandonRomano/integration-release-action
          path: ./integration-release-action

      - name: Notify Release
        uses: ./integration-release-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          integration_identifier: 'packer/brandoncorp-plugin'
          release_version: ${{ github.event.inputs.version }}
          release_sha: 'main'
