name: Notify Integration Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "A semver"
        default: 0.0.1
        required: false
jobs:
  send_notify_release_request:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Test
        run: |
          curl --request POST \
          --url https://5nw9rm117f.execute-api.us-east-1.amazonaws.com/products/packer/integrations/brandoncorp-plugin/notify-release \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "version": "${{ github.event.inputs.version }}",
            "sha": "main"
            }'
